services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: php_app
    volumes:
      - ./app:/app
    ports:
      - "9000:9000"
    environment:
      - PHP_INI_DIR=/usr/local/etc/php
    networks:
      - etl-mysql-network

  nginx:
    image: nginx:latest
    container_name: nginx_etl
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - etl-mysql-network
    depends_on:
      - php

  mysql:
    image: mysql:latest
    container_name: mysql_etl
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: etl
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d  # Папка с SQL-скриптами
    networks:
      - etl-mysql-network

  composer:
    image: composer:2
    container_name: composer_etl
    volumes:
      - ./app:/app
    working_dir: /app
    entrypoint: ["sleep", "infinity"]
    networks:
      - etl-mysql-network
    depends_on:
      - php

volumes:
  mysql-data:

networks:
  etl-mysql-network:
    name: test-etl_etl-mysql-network